title: Kadin Sayani # your name (or website title) here
logo: "/images/IMG_3464.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CS Student @ UCalgary 
  <br><br>
  Full-stack Development, Data Science, and Mobile Development
  <br><br>
  <a href="www.linkedin.com/in/kadinsayani">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-H39VG38V5D # your Google Analytics tracking ID here
